# Generated by Django 3.2.9 on 2021-11-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
